#Pagehelper配置
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countsql

# MinIO配置
#现在还没有配置好
#minio:
#  url: http://139.224.70.154:9000
#  accessKey: fileadmin
#  secretKey: fileadmin
#  bucketName: bookkeeping
#  previewExpiry: 24


server:
  port: 8090

spring:

#  数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url:
    username:
    password:

#redis 配置，放在服务器上
    redis:
      host: localhost
      port: 6379
      password: your_redis_password (if applicable)
      jedis:
        pool:
          max-active: 100  # Maximum number of connections
          max-idle: 10     # Maximum number of idle connections in the pool
          min-idle: 5      # Minimum number of idle connections in the pool
        timeout: 2000        # Connection timeout in milliseconds

mybatis:
  mapper-locations: classpath*:mapper/*Mapper.xml

# 文件上传大小限制
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
